services:
  - type: web
    name: rbcomputer-backend
    env: python
    region: oregon
    buildCommand: |
      cd backend
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: |
      cd backend
      gunicorn rbcomputer.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: rbcomputer-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
    
  - type: pserv
    name: rbcomputer-db
    env: postgresql
    region: oregon
    databaseName: rbcomputer
    databaseUser: rbcomputer_user
